#requires -Version 5.1
<#
.SYNOPSIS
    Prepares a Windows machine to build FrameVault as a static single binary.

.DESCRIPTION
    FrameVault links FFmpeg through the `ffmpeg-next` / `ffmpeg-sys-next` crates. On Windows
    it links FFmpeg (+ libx264) *statically* so the produced `framevault.exe` ships without
    FFmpeg DLLs. The static, MSVC-compatible libraries are built by vcpkg using the
    `x64-windows-static-md` triplet (static libs, dynamic CRT). This script:
      1. Clones + bootstraps vcpkg (if missing).
      2. Builds FFmpeg with the libx264 (GPL) encoder. GPL is required because the encoder
         uses libx264 (H.264 CRF 0); without it, encoding fails at runtime. This is a slow,
         one-time, from-source build (vcpkg auto-acquires nasm/cmake/ninja/msys2).
      3. Locates libclang (from an LLVM install) for bindgen.
      4. Writes .cargo\config.toml so `cargo build` routes through vcpkg's static libraries.

    Re-run this on each new machine. It is idempotent (skips work that is already done).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\setup-windows.ps1
    cargo build --release
#>
[CmdletBinding()]
param(
    # Where vcpkg lives (cloned here if absent). Kept outside the repo.
    [string]$VcpkgRoot = (Join-Path $env:USERPROFILE "vcpkg"),
    # vcpkg triplet: static libs + dynamic CRT (matches Rust's default CRT).
    [string]$Triplet = "x64-windows-static-md",
    # Force re-install of the ffmpeg port even if already present.
    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }

# --- 1. vcpkg ---------------------------------------------------------------------
$vcpkgExe = Join-Path $VcpkgRoot "vcpkg.exe"
if (-not (Test-Path $vcpkgExe)) {
    if (-not (Test-Path $VcpkgRoot)) {
        Write-Step "Cloning vcpkg into $VcpkgRoot ..."
        git clone https://github.com/microsoft/vcpkg $VcpkgRoot
    }
    Write-Step "Bootstrapping vcpkg ..."
    & (Join-Path $VcpkgRoot "bootstrap-vcpkg.bat") -disableMetrics
}
if (-not (Test-Path $vcpkgExe)) { throw "vcpkg bootstrap failed: $vcpkgExe not found" }
Write-Step "vcpkg ready at $VcpkgRoot"

# --- 2. FFmpeg 6.1.1 (static, GPL/libx264) ----------------------------------------
# ffmpeg-next 6.1 binds the pre-FFmpeg-7 API (src/media.rs uses AVCodecContext.channels /
# channel_layout, removed in FFmpeg 7), but vcpkg's current ports ship FFmpeg 8.x. Rather
# than pin vcpkg to the 2024 baseline (whose msys2 build-tool packages have been pruned
# from the mirrors), we overlay only the FFmpeg *port* at version 6.1.1 (committed under
# scripts/vcpkg-overlay/ffmpeg) on top of the current baseline. x264 and the msys2 build
# tools come from the live current baseline; only the FFmpeg source is pinned to n6.1.1.
$overlayPorts = Join-Path $repoRoot "scripts\vcpkg-overlay"
$ffmpegInstalled = Test-Path (Join-Path $VcpkgRoot "installed\$Triplet\lib\avcodec.lib")
if ($ffmpegInstalled -and -not $Force) {
    Write-Step "FFmpeg already installed for $Triplet (use -Force to rebuild)"
} else {
    Write-Step "Building FFmpeg 6.1.1[x264] for $Triplet (slow, one-time, from source) ..."
    & $vcpkgExe install "ffmpeg[avdevice,avfilter,avformat,swresample,swscale,x264]:$Triplet" `
        --overlay-ports="$overlayPorts"
    if ($LASTEXITCODE -ne 0) { throw "vcpkg install ffmpeg failed (exit $LASTEXITCODE)" }
    if (-not (Test-Path (Join-Path $VcpkgRoot "installed\$Triplet\lib\avcodec.lib"))) {
        throw "vcpkg did not produce avcodec.lib for $Triplet"
    }
}

# --- 3. libclang (LLVM) for bindgen -----------------------------------------------
Write-Step "Locating libclang (LLVM) ..."
$libclangDir = $null
$candidates = @()
if ($env:LIBCLANG_PATH) { $candidates += $env:LIBCLANG_PATH }
$clang = Get-Command clang -ErrorAction SilentlyContinue
if ($clang) { $candidates += (Split-Path -Parent $clang.Source) }
$candidates += @("C:\Program Files\LLVM\bin", "D:\Programs\LLVM\bin")

foreach ($c in $candidates) {
    if ($c -and (Test-Path (Join-Path $c "libclang.dll"))) { $libclangDir = $c; break }
}
if (-not $libclangDir) {
    throw "Could not find libclang.dll. Install LLVM (https://releases.llvm.org/) and re-run, " +
          "or set `$env:LIBCLANG_PATH to the folder containing libclang.dll."
}
Write-Host "    libclang: $libclangDir"

# --- 4. .cargo\config.toml --------------------------------------------------------
Write-Step "Writing .cargo\config.toml ..."
$cargoDir = Join-Path $repoRoot ".cargo"
New-Item -ItemType Directory -Force -Path $cargoDir | Out-Null
$vcpkgEsc    = $VcpkgRoot.Replace('\', '\\')
$libclangEsc = $libclangDir.Replace('\', '\\')
$config = @"
# Generated by scripts/setup-windows.ps1 — see that script for details.
# Routes ffmpeg-sys-next through vcpkg's static libraries. Do NOT add FFMPEG_DIR here;
# it would short-circuit vcpkg discovery in the build script.
[env]
VCPKG_ROOT = "$vcpkgEsc"
VCPKGRS_TRIPLET = "$Triplet"
LIBCLANG_PATH = "$libclangEsc"
"@
# Write UTF-8 *without* a BOM: Windows PowerShell 5.1's `Set-Content -Encoding UTF8`
# emits a BOM, which cargo's TOML parser rejects. .NET writes BOM-free on both 5.1 and 7+.
[System.IO.File]::WriteAllText(
    (Join-Path $cargoDir "config.toml"),
    ($config -replace "`r`n", "`n"),
    (New-Object System.Text.UTF8Encoding $false))

Write-Host ""
Write-Step "Done. Now build the static binary with:"
Write-Host "    cargo build --release" -ForegroundColor Green
